select* from VERSOES
;

SELECT S.ID_SISTEMA AS CODIGO_DO_SISTEMA , 
S.CRIADOEM AS CreatedON, 
U.NOME AS CADASTRADO_POR, 
PER.NOME AS PERMISSAO 
FROM SISTEMA S  
INNER JOIN USUARIO U ON  S.ID_USUARIO=U.ID_USUARIO 
INNER JOIN PERMISSAO PER ON U.ID_PERMISSAO=PER.ID_PERMISSAO    
ORDER BY S.ID_SISTEMA ASC
;

SELECT U.NOME AS USUARIO, V.ID_VERSAO AS VERSAO_COD, V.ID_SISTEMA AS SISTEMA_PAI 
, D.NOME AS DEPARTAMENTO 
FROM VERSOES V INNER JOIN SISTEMA S ON S.ID_SISTEMA=V.ID_SISTEMA  
INNER JOIN USUARIO U ON U.ID_USUARIO=S.ID_USUARIO 
INNER JOIN DEPARTAMENTO D ON U.ID_DEPARTAMENTO=D.ID_DEPARTAMENTO ORDER BY U.NOME ASC, V.ID_VERSAO ASC  
;

SELECT U.NOME AS USUARIO, V.ID_VERSAO AS VERSAO_COD, V.ID_SISTEMA AS SISTEMA_PAI 
, D.NOME AS DEPARTAMENTO 
FROM VERSOES V INNER JOIN SISTEMA S ON S.ID_SISTEMA=V.ID_SISTEMA  
INNER JOIN USUARIO U ON U.ID_USUARIO=S.ID_USUARIO 
INNER JOIN DEPARTAMENTO D ON U.ID_DEPARTAMENTO=D.ID_DEPARTAMENTO WHERE D.NOME='DESIGN' ORDER BY U.NOME ASC, V.ID_VERSAO ASC  
;

SELECT U.NOME AS USUARIO, V.ID_VERSAO AS VERSAO_COD, V.ID_SISTEMA AS SISTEMA_PAI 
, D.NOME AS DEPARTAMENTO 
FROM VERSOES V INNER JOIN SISTEMA S ON S.ID_SISTEMA=V.ID_SISTEMA  
INNER JOIN USUARIO U ON U.ID_USUARIO=S.ID_USUARIO 
INNER JOIN DEPARTAMENTO D ON U.ID_DEPARTAMENTO=D.ID_DEPARTAMENTO WHERE D.NOME='DESIGN' ORDER BY U.NOME ASC, V.ID_VERSAO ASC  
;

SELECT DISTINCT U.NOME AS USUARIO, V.ID_VERSAO AS VERSAO_COD, V.ID_SISTEMA AS SISTEMA_PAI 
, D.NOME AS DEPARTAMENTO 
FROM VERSOES V INNER JOIN SISTEMA S ON S.ID_SISTEMA=V.ID_SISTEMA  
INNER JOIN USUARIO U ON U.ID_USUARIO=S.ID_USUARIO 
INNER JOIN DEPARTAMENTO D ON U.ID_DEPARTAMENTO=D.ID_DEPARTAMENTO WHERE D.NOME='DESIGN' ORDER BY U.NOME ASC, V.ID_VERSAO ASC  
;

SELECT DISTINCT(U.NOME) AS USUARIO, V.ID_VERSAO AS VERSAO_COD, V.ID_SISTEMA AS SISTEMA_PAI 
, D.NOME AS DEPARTAMENTO 
FROM VERSOES V INNER JOIN SISTEMA S ON S.ID_SISTEMA=V.ID_SISTEMA  
INNER JOIN USUARIO U ON U.ID_USUARIO=S.ID_USUARIO 
INNER JOIN DEPARTAMENTO D ON U.ID_DEPARTAMENTO=D.ID_DEPARTAMENTO WHERE D.NOME='DESIGN' ORDER BY U.NOME ASC, V.ID_VERSAO ASC  
;

SELECT DISTINCT(U.NOME) AS USUARIO, V.ID_VERSAO AS VERSAO_COD, V.ID_SISTEMA AS SISTEMA_PAI 
, D.NOME AS DEPARTAMENTO 
FROM VERSOES V INNER JOIN SISTEMA S ON S.ID_SISTEMA=V.ID_SISTEMA  
INNER JOIN USUARIO U ON U.ID_USUARIO=S.ID_USUARIO 
INNER JOIN DEPARTAMENTO D ON U.ID_DEPARTAMENTO=D.ID_DEPARTAMENTO WHERE D.NOME='DESIGN' ORDER BY U.NOME ASC, V.ID_VERSAO ASC  
;

SELECT DISTINCT U.NOME AS USUARIO, V.ID_VERSAO AS VERSAO_COD, V.ID_SISTEMA AS SISTEMA_PAI 
, D.NOME AS DEPARTAMENTO 
FROM VERSOES V INNER JOIN SISTEMA S ON S.ID_SISTEMA=V.ID_SISTEMA  
INNER JOIN USUARIO U ON U.ID_USUARIO=S.ID_USUARIO 
INNER JOIN DEPARTAMENTO D ON U.ID_DEPARTAMENTO=D.ID_DEPARTAMENTO WHERE D.NOME='DESIGN' ORDER BY U.NOME ASC, V.ID_VERSAO ASC  
;

SELECT DISTINCT U.NOME AS USUARIO, V.ID_VERSAO AS VERSAO_COD, V.ID_SISTEMA AS SISTEMA_PAI 
, D.NOME AS DEPARTAMENTO 
FROM VERSOES V INNER JOIN SISTEMA S ON S.ID_SISTEMA=V.ID_SISTEMA  
INNER JOIN USUARIO U ON U.ID_USUARIO=S.ID_USUARIO 
INNER JOIN DEPARTAMENTO D ON U.ID_DEPARTAMENTO=D.ID_DEPARTAMENTO WHERE D.NOME='DESIGN' ORDER BY U.NOME ASC, V.ID_VERSAO ASC  
;

SELECT  U.NOME AS USUARIO, V.ID_VERSAO AS VERSAO_COD, V.ID_SISTEMA AS SISTEMA_PAI 
, D.NOME AS DEPARTAMENTO 
FROM VERSOES V INNER JOIN SISTEMA S ON S.ID_SISTEMA=V.ID_SISTEMA  
INNER JOIN USUARIO U ON U.ID_USUARIO=S.ID_USUARIO 
INNER JOIN DEPARTAMENTO D ON U.ID_DEPARTAMENTO=D.ID_DEPARTAMENTO WHERE D.NOME='DESIGN' ORDER BY U.NOME ASC, V.ID_VERSAO ASC  
;

SELECT * FROM SISTEMA
;

SELECT * FROM SISTEMA
;

SELECT * FROM SISTEMA
;

SELECT * FROM SISTEMA
;

SELECT * FROM USUARIO
;

SELECT * FROM DEPARTAMENTO
;

SELECT * FROM SISTEMA
;

SELECT * FROM USUARIO
;

SELECT * FROM DEPARTAMENTO
;

 SELECT D.NOME, COUNT(*) FROM DEPARTAMENTO D  
 INNER JOIN USUARIO U ON U.ID_DEPARTAMENTO=D.ID_DEPARTAMENTO 
 INNER JOIN  SISTEMA S ON S.ID_USUARIO=U.ID_USUARIO GROUP BY D.NOME
;

SELECT * FROM SISTEMA
;

SELECT * FROM USUARIO
;

SELECT * FROM DEPARTAMENTO
;

 SELECT D.NOME AS DEPARTAMENTO, COUNT(*) FROM DEPARTAMENTO D  
 INNER JOIN USUARIO U ON U.ID_DEPARTAMENTO=D.ID_DEPARTAMENTO 
 INNER JOIN  SISTEMA S ON S.ID_USUARIO=U.ID_USUARIO GROUP BY D.NOME
;

 SELECT D.NOME AS DEPARTAMENTO, COUNT(*) FROM DEPARTAMENTO D  
 INNER JOIN USUARIO U ON U.ID_DEPARTAMENTO=D.ID_DEPARTAMENTO 
 INNER JOIN  SISTEMA S ON S.ID_USUARIO=U.ID_USUARIO GROUP BY D.NOME
;

 SELECT D.NOME AS DEPARTAMENTO, COUNT(*) FROM DEPARTAMENTO D  
 INNER JOIN USUARIO U ON U.ID_DEPARTAMENTO=D.ID_DEPARTAMENTO 
 INNER JOIN  SISTEMA S ON S.ID_USUARIO=U.ID_USUARIO GROUP BY D.NOME
;

SELECT * FROM SISTEMA
;

SELECT * FROM USUARIO
;

SELECT * FROM DEPARTAMENTO
;

SELECT * FROM SISTEMA
;

 SELECT D.NOME AS DEPARTAMENTO, COUNT(*) FROM DEPARTAMENTO D  
 INNER JOIN USUARIO U ON U.ID_DEPARTAMENTO=D.ID_DEPARTAMENTO 
 INNER JOIN  SISTEMA S ON S.ID_USUARIO=U.ID_USUARIO GROUP BY D.NOME
;

SELECT * FROM SISTEMA
;

SELECT * FROM USUARIO
;

 SELECT D.NOME AS DEPARTAMENTO, COUNT(*) FROM DEPARTAMENTO D  
 INNER JOIN USUARIO U ON U.ID_DEPARTAMENTO=D.ID_DEPARTAMENTO 
 INNER JOIN  SISTEMA S ON S.ID_USUARIO=U.ID_USUARIO GROUP BY D.NOME
;

SELECT * FROM DEPARTAMENTO
;

SELECT P.NOME AS PERMISSAO, COUNT(*) AS QUANTIDADE_DE_RESGISTROS 
FROM PERMISSAO P INNER JOIN USUARIO U  ON P.ID_DEPARTAMENTO=U.ID_DEPARTAMENTO 
INNER JOIN SISTEMA S ON S.ID_USUARIO=U.ID_USUARIO  
INNER JOIN VERSOES V ON V.ID_SISTEMA=S.ID_SISTEMA GROUP BY P.NOME
;

SELECT * FROM DEPARTAMENTO
;

SELECT P.NOME AS PERMISSAO, COUNT(*) AS QUANTIDADE_DE_RESGISTROS 
FROM PERMISSAO P INNER JOIN USUARIO U  ON P.ID_PERMISSAO=U.ID_PERMISSAO 
INNER JOIN SISTEMA S ON S.ID_USUARIO=U.ID_USUARIO  
INNER JOIN VERSOES V ON V.ID_SISTEMA=S.ID_SISTEMA GROUP BY P.NOME
;

SELECT * FROM VERSOES 
;

SELECT P.NOME AS PERMISSAO, COUNT(*) AS QUANTIDADE_DE_RESGISTROS 
FROM PERMISSAO P INNER JOIN USUARIO U  ON P.ID_PERMISSAO=U.ID_PERMISSAO 
INNER JOIN SISTEMA S ON S.ID_USUARIO=U.ID_USUARIO  
INNER JOIN VERSOES V ON V.ID_SISTEMA=S.ID_SISTEMA GROUP BY P.NOME
;

SELECT P.NOME AS PERMISSAO, COUNT(*) AS QUANTIDADE_DE_RESGISTROS 
FROM PERMISSAO P INNER JOIN USUARIO U  ON P.ID_PERMISSAO=U.ID_PERMISSAO 
INNER JOIN SISTEMA S ON S.ID_USUARIO=U.ID_USUARIO  
INNER JOIN VERSOES V ON V.ID_SISTEMA=S.ID_SISTEMA HAVING P.NOME='DBA'
;

SELECT * FROM SISTEMA
;

SELECT * FROM USUARIO
;

SELECT * FROM DEPARTAMENTO
;

SELECT P.NOME AS PERMISSAO, COUNT(P.NOME) AS QUANTIDADE_DE_RESGISTROS 
FROM PERMISSAO P INNER JOIN USUARIO U  ON P.ID_PERMISSAO=U.ID_PERMISSAO 
INNER JOIN SISTEMA S ON S.ID_USUARIO=U.ID_USUARIO  
INNER JOIN VERSOES V ON V.ID_SISTEMA=S.ID_SISTEMA HAVING P.NOME='DBA'
;

SELECT P.NOME AS PERMISSAO, COUNT(*) AS QUANTIDADE_DE_RESGISTROS 
FROM PERMISSAO P INNER JOIN USUARIO U  ON P.ID_PERMISSAO=U.ID_PERMISSAO 
INNER JOIN SISTEMA S ON S.ID_USUARIO=U.ID_USUARIO  
INNER JOIN VERSOES V ON V.ID_SISTEMA=S.ID_SISTEMA GROUP BY P.NOME
;

SELECT P.NOME AS PERMISSAO, COUNT(P.NOME) AS QUANTIDADE_DE_RESGISTROS 
FROM PERMISSAO P INNER JOIN USUARIO U  ON P.ID_PERMISSAO=U.ID_PERMISSAO 
INNER JOIN SISTEMA S ON S.ID_USUARIO=U.ID_USUARIO  
INNER JOIN VERSOES V ON V.ID_SISTEMA=S.ID_SISTEMA GROUP BY P.NOME
;

SELECT * FROM SISTEMA
;

SELECT * FROM USUARIO
;

SELECT * FROM DEPARTAMENTO
;

SELECT P.NOME AS PERMISSAO, DISTINCT COUNT(P.NOME) AS QUANTIDADE_DE_RESGISTROS 
FROM PERMISSAO P INNER JOIN USUARIO U  ON P.ID_PERMISSAO=U.ID_PERMISSAO 
INNER JOIN SISTEMA S ON S.ID_USUARIO=U.ID_USUARIO  
INNER JOIN VERSOES V ON V.ID_SISTEMA=S.ID_SISTEMA GROUP BY P.NOME
;

SELECT * FROM SISTEMA
;

SELECT * FROM USUARIO
;

SELECT * FROM DEPARTAMENTO
;

SELECT P.NOME AS PERMISSAO, DISTINCT (COUNT(P.NOME)) AS QUANTIDADE_DE_RESGISTROS 
FROM PERMISSAO P INNER JOIN USUARIO U  ON P.ID_PERMISSAO=U.ID_PERMISSAO 
INNER JOIN SISTEMA S ON S.ID_USUARIO=U.ID_USUARIO  
INNER JOIN VERSOES V ON V.ID_SISTEMA=S.ID_SISTEMA GROUP BY P.NOME
;

SELECT * FROM SISTEMA
;

SELECT * FROM USUARIO
;

SELECT * FROM DEPARTAMENTO
;

SELECT P.NOME AS PERMISSAO, COUNT(P.NOME) AS QUANTIDADE_DE_RESGISTROS 
FROM PERMISSAO P INNER JOIN USUARIO U  ON P.ID_PERMISSAO=U.ID_PERMISSAO 
INNER JOIN SISTEMA S ON S.ID_USUARIO=U.ID_USUARIO  
INNER JOIN VERSOES V ON V.ID_SISTEMA=S.ID_SISTEMA GROUP BY P.NOME
;

 SELECT * FROM USUARIO
;

 SELECT DISTINCT U.NOME FROM USUARIO U
;

SELECT U.NOME FROM USUARIO U
;

 SELECT DISTINCT U.NOME AS NOME_PARA_IMPRESSAO FROM USUARIO U
;

 SELECT DISTINCT U.NOME AS NOME_PARA_IMPRESSAO FROM USUARIO U ORDER BY U.NOME ASC
;