CREATE TABLE VERSOES  
( 
 	ID_VERSAO NUMERIC(10)NOT NULL,  
	VERSAO VARCHAR2(20) NOT NULL,  
	NOVIDADES VARCHAR2(250) NOT NULL,  
 	ID_SISTEMA NUMERIC(10) NOT NULL,  
 	CONSTRAINT VERSOES_PK PRIMARY KEY(ID_VERSAO)ENABLE  
)
;

CREATE TABLE SISTEMA  
 
( 
	ID_SISTEMA NUMERIC(10) NOT NULL,  
	ATIVO NUMBER(1) DEFAULT 1 NOT NULL , 
	ID_USUARIO NUMERIC(10) NOT NULL , 
	CRIADOEM DATE DEFAULT SYSDATE , 
	CONSTRAINT SISTEMA_PK PRIMARY KEY(ID_SISTEMA)ENABLE  
)
;

CREATE TABLE  USUARIO 
 
(  
	ID_USUARIO NUMERIC(10) NOT NULL, 
	NOME VARCHAR2(120) NOT NULL, 
	ID_DEPARTAMENTO NUMERIC(10)NOT NULL, 
	ID_PERMISSAO NUMERIC(10)NOT NULL, 
	CONSTRAINT USUARIO_PK PRIMARY KEY(ID_USUARIO)ENABLE 
)
;

CREATE TABLE DEPARTAMENTO 
 
( 	 
	ID_DEPARTAMENTO NUMERIC(10) NOT NULL, 
	NOME VARCHAR2(120) NOT NULL, 
	CONSTRAINT DEPARTAMENTO_PK PRIMARY KEY(ID_DEPARTAMENTO)ENABLE 
)
;

CREATE TABLE PERMISSAO 
 
( 
	ID_PERMISSAO NUMERIC(10) NOT NULL, 
	NOME VARCHAR2(100) NOT NULL, 
	CONSTRAINT PERMISSAO_PK PRIMARY KEY (ID_PERMISSAO)ENABLE		 
)
;

ALTER TABLE VERSOES 
	ADD CONSTRAINT FK_SISTEMA 
  	FOREIGN KEY (ID_SISTEMA) 
  	REFERENCES SISTEMA(ID_SISTEMA) ON DELETE CASCADE
;

ALTER TABLE SISTEMA 
	ADD CONSTRAINT FK_USUARIO 
  	FOREIGN KEY (ID_USUARIO) 
  	REFERENCES USUARIO(ID_USUARIO)
;

ALTER TABLE SISTEMA
	ADD CONSTRAINT VALORES_SISTEMA
	ATIVO (ONOFF in (1, 0))
;

ALTER TABLE USUARIO 
ADD CONSTRAINT FK_DEPARTAMENTO 
	FOREIGN KEY (ID_DEPARTAMENTO) 
	REFERENCES DEPARTAMENTO(ID_DEPARTAMENTO)
;

ALTER TABLE USUARIO 
ADD CONSTRAINT FK_PERMISSAO 
  	FOREIGN KEY (ID_PERMISSAO) 
	REFERENCES PERMISSAO(ID_PERMISSAO)
;
			 
CREATE SEQUENCE VERSOES_SEQ nocache
;

CREATE SEQUENCE SISTEMA_SEQ nocache
;

CREATE SEQUENCE USUARIO_SEQ nocache
;

CREATE SEQUENCE DEPARTAMENTO_SEQ nocache
;

CREATE SEQUENCE PERMISSAO_SEQ nocache start with 100
;
