
DROP SEQUENCE VERSOES_SEQ;
DROP SEQUENCE SISTEMA_SEQ;
DROP SEQUENCE USUARIO_SEQ;
DROP SEQUENCE DEPARTAMENTO_SEQ;
DROP SEQUENCE PERMISSAO_SEQ;

DROP TABLE VERSOES CASCADE CONSTRAINTS;
DROP TABLE SISTEMA CASCADE CONSTRAINTS;
DROP TABLE USUARIO CASCADE CONSTRAINTS;
DROP TABLE DEPARTAMENTO CASCADE CONSTRAINTS;
DROP TABLE PERMISSAO CASCADE CONSTRAINTS;
